# Partimos de la imagen base de Airflow
FROM apache/airflow:2.9.3-python3.9

# Usamos el usuario airflow para instalar providers
USER airflow

# Instalamos los providers necesarios para PostgreSQL y Kafka
# Pin apache-airflow to 2.9.3 to prevent upgrade to 3.x
RUN pip install --no-cache-dir \
    "apache-airflow==2.9.3" \
    apache-airflow-providers-postgres \
    apache-airflow-providers-apache-kafka \
    psycopg2-binary
